### ISSUE TITLE
Version 0.0.5+ not workintg with Gradle 8

### ISSUE THREAD

**Issue by GMCristiano** [christiandeange/aaraar#4]
Version 0.0.4 works fine, but version 0.0.5+ gets this error:

Could not create task ':module:packageReleaseAar'.
   > 'com.android.build.api.dsl.PackagingOptions com.android.build.api.dsl.LibraryExtension.getPackagingOptions()'

Gradle Version: 8.1.1
AGP: 8.0.1

Thank again for this plugin.

**Comment by GMCristiano** [comment]
Some extra info:

https://stackoverflow.com/questions/75172062/how-to-replace-deprecated-packagingoptions-in-android-gradle-build-files

**Comment by christiandeange** [comment]
@GMCristiano thanks for the report! I think it's because in that version we started to respect the packaging options' resource exclude rules to filter out some additional files from the final AAR. It looks like the classes for this API were renamed in AGP 8, though.

I just published a commit that I believe addresses this. Can you test the latest `0.0.8-SNAPSHOT` version to verify that this is now solved for AGP 8?

**Comment by GMCristiano** [comment]
Not public? https://repo1.maven.org/maven2/sh/christian/aaraar/sh.christian.aaraar.gradle.plugin/

**Comment by GMCristiano** [comment]
now it compiles. 

```
maven {
    url 'https://s01.oss.sonatype.org/content/repositories/snapshots/'
}
```

**Comment by christiandeange** [comment]
`0.0.8` is now published and will be available on Maven Central shortly. Make sure to consult the [readme](https://github.com/christiandeange/aaraar#readme) and [change log](https://github.com/christiandeange/aaraar/blob/main/CHANGELOG.md#version-008) for updates on how this new version works.
